# Stage 1: Build the application
FROM node:18-alpine AS builder

WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm install --production

COPY backend/ ./

RUN npm prune --production

# Stage 2: Run the application
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/server.js ./server.js
COPY --from=builder /app/src ./src

EXPOSE 4000

CMD ["node", "server.js"]