version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: taskflow_backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      SQLITE_DB_PATH: ./data/taskflow.sqlite # Path inside the container
      JWT_SECRET: e8a2b7c1d6f5e4a3b2c1d0e9f8a7b6c5
      FRONTEND_URL: http://localhost:8082
    volumes:
      - backend_data:/app/data # Persist SQLite database file
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    container_name: taskflow_frontend
    ports:
      - "8082:8082" # Expose frontend on 8082
    depends_on:
      - backend
    restart: always

volumes:
  backend_data: